channels:
- conda-forge
dependencies:
- python=3.13.5
- pip<=25.1
- pip:
  - mlflow==3.6.0
  - cloudpickle==3.1.2
  - numpy==2.3.1
  - pandas==2.3.1
  - psutil==5.9.0
  - pyarrow==22.0.0
  - scikit-learn==1.7.2
  - scipy==1.16.2
name: mlflow-env
